// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  EthereumCall,
  EthereumEvent,
  SmartContract,
  EthereumValue,
  JSONValue,
  TypedMap,
  Entity,
  EthereumTuple,
  Bytes,
  Address,
  BigInt,
  CallResult
} from "@graphprotocol/graph-ts";

export class KRC20SymbolBytes extends SmartContract {
  static bind(address: Address): KRC20SymbolBytes {
    return new KRC20SymbolBytes("KRC20SymbolBytes", address);
  }

  symbol(): Bytes {
    let result = super.call("symbol", []);

    return result[0].toBytes();
  }

  try_symbol(): CallResult<Bytes> {
    let result = super.tryCall("symbol", []);
    if (result.reverted) {
      return new CallResult();
    }
    let value = result.value;
    return CallResult.fromValue(value[0].toBytes());
  }
}
